name: 'Get created_at timestamp of last workflow'
description: 'Get created_at timestamp of last workflow run on current branch.'
branding:
  icon: 'arrow-left'
  color: 'yellow'
inputs:
  github_token:
    description: Secret GitHub API token to use for making API requests.
    default: ${{ github.token }}
    required: true
outputs:
  last_created_at:
    description: "Last time workflow ran on current branch"
    value: ${{ steps.last_created_at.outputs.last_created_at }}
runs:
  using: "composite"
  steps:
    - name: Get branch name
      shell: bash
      run: |
        if [[ ${GITHUB_EVENT_NAME} == "pull_request" ]]
        then
           echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF})" >> $GITHUB_ENV
           echo "Branch name: ${GITHUB_HEAD_REF}"
        else
           echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
           echo "Branch name: ${GITHUB_REF#refs/heads/}"        
        fi
    - name: Get workflow id
      shell: bash
      run: |
        WORKFLOW_ID=$(curl --header 'authorization: Bearer ${{ inputs.github_token }}' \
                           --header 'content-type: application/json' \
        ${{ github.api_url }}/repos/${{ github.repository }}/actions/runs/${{ github.run_id }} | jq -r .workflow_id)
        echo "WORKFLOW_ID=$WORKFLOW_ID" >> $GITHUB_ENV
        echo "Workflow id: ${WORKFLOW_ID}"
    - name: Get previous build status
      shell: bash
      id: last_completed_at
      run: |
        last_created_at=$(curl --silent --header 'authorization: Bearer ${{ inputs.github_token }}' \
                                    --header 'content-type: application/json' \
        "${{ github.api_url }}/repos/${{ github.repository }}/actions/workflows/${{ env.WORKFLOW_ID }}/runs?per_page=1&status=completed&branch=${{ env.BRANCH_NAME }}" \
        | jq -r .workflow_runs[0].created_at)
        echo "last_created_at=$last_created_at" >> $GITHUB_OUTPUT
        echo "Previous build created at: $last_created_at"
